Assignments/Assignment 4/Prototype/minsp/Login/routes.py
import random, os
from flask import render_template, url_for, flash, redirect, request, Blueprint, Response, send_from_directory
from minsp import app, conn, bcrypt
from minsp.forms import CustomerLoginForm, GraphForm, SearchForm
from flask_login import login_user, current_user, logout_user, login_required
from minsp.models import *#Customers, select_Customers, select_Health_Prof, select_test_res,select_Result_Types,select_specific_type_res
from minsp.helper_functions import *
import os


Login = Blueprint('Login', __name__)

posts = [{}]


@Login.route("/")
@Login.route("/home")
def home():
    return render_template('home.html', posts=posts)


@Login.route("/about")
def about():
    return render_template('about.html', title='About')


@Login.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('Login.home'))
    form = CustomerLoginForm()
    if form.validate_on_submit():
        user = select_Customers(form.id.data)
        # need some salt for that
        if user != None: # and bcrypt.check_password_hash(user[1], form.password.data):
            login_user(user, remember=form.remember.data)
            flash('Login successful.','success')
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('Login.home'))
        else:
            flash('Login Unsuccessful. Please check identifier and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@Login.route("/logout")
def logout():
    print_debug(os.getcwd())
    #Cleaning up images that was created during session
    base = "minsp/static/images"
    files = os.listdir(base)
    for f in files:
        if str(current_user[0]) in f:
            os.remove(base+'/'+f)
    logout_user()

    return redirect(url_for('Login.home'))


@Login.route("/graph", methods=['GET', 'POST'])
@login_required
def graph():
    form = GraphForm()
    types_of_res = select_Result_Types(current_user[0])
    types_of_res = unpack(types_of_res)
    form.types.choices = types_of_res

    if form.is_submitted():
        selected = form.types.raw_data
        res = select_specific_type_res_date(current_user[0], selected[0],form.from_date, form.to_date)
        filename = create_fig(selected, res, current_user[0])
        return render_template('graph.html', name='new_plot', url=filename, form=form)

    else:
        return render_template('graph.html', form=form)


@Login.route("/health")
@login_required
def health():
    doctor = select_Health_Prof(current_user[0])
    return render_template("health.html", doctor=doctor, title="Contacts")


@Login.route("/results", methods=['GET', 'POST'])
@login_required
def results():
    form = SearchForm()
    cpr = current_user[0]
    types = select_test_list(cpr)
    if form.is_submitted():
        search_text = form.search.raw_data[0]
        types = search_test_res(cpr, search_text)
        
    if types == None:
        types = []
    return render_template("results.html", types=types, title="Test Resulter", form=form)

Assignments/Assignment 4/Prototype/minsp/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>Vores Information </h1>
    <p style="color:#A9A9A9">AL20200612</p>
	<p>Dette er vores prototype til faget Udvikling af informationssystemer (UIS)</p>

	<p>Dette er vores prototype der fremviser forskellige aspekter vi mener kunne
		forbedre vores gruppes oplevelse når de gør brug af platformen i deres daglige virke</p>

<p>Udviklet og designet af: Jasmin Pedersen, Jonatan Geysner Hvidberg & Emil Bæk Henriksen</p>



<div class="qoutes" style="color: #248242"><blockquote><em> "To err is human, but to really foul things up you need a computer."</em></blockquote></div>
            <div class="names" style="color: #248242">- Paul R. Ehrlich </div>
{% endblock content %}

Assignments/Assignment 4/Prototype/minsp/templates/graph.html
{% extends "layout.html" %}
{% block content %}

<div class="content-section">
    <form method="POST" action="">
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">Se dine resultater som en graf</legend>
        <div class="form-group">
            {{ form.from_date.label(class="form-control-label") }}
            {% if form.from_date.errors %}
                {{ form.from_date(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.from_date.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.from_date(class="form-control form-control-lg") }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.to_date.label(class="form-control-label") }}
            {% if form.to_date.errors %}
                {{ form.to_date(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.from_date.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.to_date(class="form-control form-control-lg") }}
            {% endif %}
        </div>
        <div class="form-group">
    <div> Vælg type for graf</div> 
    {{ form.types(class="btn btn-outline-info") }}
    </div>
    </fieldset>
    <div class="form-group">
        {{ form.submit(class="btn btn-outline-info") }}
    </div>
    {% if form.submit.data%}            
        <img src="{{ url }}" height="420" width="420">
    {% else %}
        <div></div>
    {% endif %}
</div>

{% endblock content %}

Assignments/Assignment 4/Prototype/minsp/templates/health.html
{% extends "layout.html" %}
{% block content %}

<div class="content-section">
	<form method="POST" action="">
		<div class="form-group">
      {% if doctor %}
			{% for doc in doctor %}
        <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
              <h3 class="article-content1"> {{ doc[3] }}</h3>

            </div>
              <p class="article-content0">{{ doc[0] }} </p>
            <p class="article-content">Adresse: {{ doc[2] }}</p>
            <p class="article-content2">Telefon: {{ doc[1] }}</p>
          </div>
        </article>
    {% endfor %}
    {% else %}
    <h2><a class="article-title" href="#"> Ingen læge tilknyttet</a></h2>
    {% endif %}
	</div>
</div>
	
{% endblock content %}

Assignments/Assignment 4/Prototype/minsp/templates/home.html
{% extends "layout.html" %}
{% block content %}


<article class="media content-section" style="background-color:#f0ec0c">
  <div class="media-body">
    <div class="article-metadata">
      <a href="https://www.sst.dk/da/corona" style="text-align: center;"><h2><u>Nyheder om COVID-19</h2></u></a>
    </div>
  </div>
</article>
{% for post in posts %}
{% if current_user.is_authenticated %}

<main class="container" role="main"> 
  <div class="row">
    <div class="col-md-8">
      <article class="content-section">
        <div class="media-body">
          <div class="article-metadata">
            <h3>Min Profil</h3>
              <a class="mr-2" href="#">{{ post.author }}</a>
              <small class="text-muted">{{ post.date_posted }}</small>
          </div>
          <h2><a class="article-title" href="#">{{ post.title }}</a></h2>
          <p class="article-content">{{ post.content }}</p>

          <a class="nav-item nav-link"> <p> &#128100 </p> {{ current_user[2] }} </a>
          <a class="nav-item nav-link"> <p> &#128222 </p> {{ current_user[4] }} </a>
          <a class="nav-item nav-link"> <p> &#128236 </p> {{ current_user[2].replace(" ","_")+current_user[6] }} </a>
          </div>
        </div>
{% else %}
        <div></div>
        
      </article>
 
{% endif %}
{% endfor %}
     
        </article>
{% if current_user.is_authenticated %}
        <div class="col-md-4"> 
        <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
                <h3>Mine Genveje</h3>
          <a class="nav-item nav-link" href="{{ url_for('Login.results') }}"> <p> &#128451</p> Mine Testresultater </a>
          <a class="nav-item nav-link" href="{{ url_for('Login.health') }}"> <p> &#128101 </p> Mine Læger</a>
          <a class="nav-item nav-link" href="{{ url_for('Login.graph') }}"> <p> &#128201 </p> Mine Grafer</a>
          </div>
        </div>
        </div>
{% else %}
            <div></div>
{% endif %}
            
    </main>

    
{% endblock content %}

Assignments/Assignment 4/Prototype/minsp/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="{{url_for('static',filename='favicon.ico')}}" type="image/x-icon">
    <link rel="icon" href="{{url_for('static',filename='favicon.ico')}}" type="image/x-icon">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    
    {% if title %}
        <title>UIS Prototype - {{ title }}</title>
    {% else %}
        <title>UIS Prototype</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/"> &#128153 MinSP</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('Login.home') }}">Hjem</a>
              {% if current_user.is_authenticated %}
                <li class="dropdown">
                 <a href="#" class="nav-item nav-link dropdown-toggle" data-toggle="dropdown">Mine Muligheder<b class="caret"></b></a>
                 <ul class="dropdown-menu">
                    <li><a class="nav-item nav-link nav-sub-item" href="{{ url_for('Login.results') }}">Mine Testresultater</a></li>
                    <li class="divider"></li>
                    <li><a class="nav-item nav-link nav-sub-item" href="{{ url_for('Login.health') }}">Mine Læger</a></li>
                    <li class="divider"></li>
                    <li><a class="nav-item nav-link nav-sub-item" href="{{ url_for('Login.graph') }}">Mine Grafer</a></li>
                    <li class="divider"></li>
                 </ul>
               </li>
              {% else %}
              {% endif %}
              <a class="nav-item nav-link" href="{{ url_for('Login.about') }}">Vores Information</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('Login.logout') }}">Log Ud</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('Login.login') }}">Log Ind</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
      </div>
    </main>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

Assignments/Assignment 4/Prototype/minsp/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.id.label(class="form-control-label") }}
                    {% if form.id.errors %}
                        {{ form.id(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.id.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.id(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
            <small class="text-muted">
                <a href="#">Glemt Password?</a>
            </small>
            <small class="text-muted ml-2">
                {% if is_employee %}
                    <a href="/login?is_employee=false">Customer login?</a>
                {% else %}
                    <a href="/login?is_employee=true">Employee login?</a>
                {%  endif %}
            </small>
        </form>
    </div>
{% endblock content %}

Assignments/Assignment 4/Prototype/minsp/templates/results.html
{% extends "layout.html" %}
{% block content %}

<!--Should be in the CSS file, but it is here for now-->
<style type='text/css'>
        table.test { border-collapse: collapse; }
        table.test td { border-bottom: 1px solid black; }
</style>
<!--Should be in the CSS file, but it is here for now-->

<form method="POST" action="">
<div>
	<fieldset class="form-group">
		<div class="form-group">
            {{ form.search.label(class="form-control-label") }}
            {% if form.search.errors %}
                {{ form.search(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.search.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.search(class="form-control form-control-lg") }}
            {% endif %}
        </div>
	</fieldset>
 <div class="form-group">
    {{ form.submit(class="btn btn-outline-info") }}
	</div>
</div>
<div class="content-section">
	{% if types != [] %}
		<div class="form-group">
			{% set id = [] %}


			{% for r in types %}

			{%if id==[] %}
			<div></div> <!--empty div to create the correct layout-->
			{%endif%}

			{%if r[0] != id[-1]%}
			</table>
			</div>
		</article>
		<article class="media content-section">
			<div class="media-body">
				<h2><a class="article-title" href="#">{{ r[1] }}</a></h2>
				<table class='test' style="width:100%">
					<tr>
						<td>{{ r[3] }}</td>
						<td>{{ r[4] }}</td>
						<td>{{ r[2] }}</td>
					</tr>

				{%else%}
				<tr>
					<td>{{ r[3] }}</td>
					<td>{{ r[4] }}</td>
					<td>{{ r[2] }}</td>
				</tr>
				{%endif%}

				{% if id.append(r[0]) %}{% endif %}
    {% endfor %}
	</div>
	{% else %}
	<div>
		<h2><a class="article-title" href="#">Ingen test resultater fundet</a></h2>
	</div>
	{% endif %}
</div>
{% endblock content %}