UIS_Prototype_v1/UIS_Prototype-master/bank/Customer/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from bank import app, conn, bcrypt
from bank.forms import DepositForm, InvestForm
from flask_login import current_user
from bank.models import CheckingAccount, InvestmentAccount, update_CheckingAccount
from bank.models import select_investments_with_certificates, select_investments, select_investments_certificates_sum
import sys, datetime

Customer = Blueprint('Customer', __name__)

@Customer.route("/invest", methods=['GET', 'POST'])
def invest():
    if not current_user.is_authenticated:
        flash('Please Login.','danger')
        return redirect(url_for('Login.login'))
    #form = InvestForm()
    #investments = select_investments(current_user.CPR_number)
    investment_certificates = select_investments_with_certificates(current_user.get_id())
    investment_sums = select_investments_certificates_sum(current_user.get_id())
    return render_template('invest.html', title='Investments', inv_cd_list=investment_certificates
    , inv_sums=investment_sums)
    

@Customer.route("/deposit", methods=['GET', 'POST'])
def deposit():
    if not current_user.is_authenticated:
        flash('Please Login.','danger')
        return redirect(url_for('Login.login'))
    form = DepositForm()
    if form.validate_on_submit():
        amount=form.amount.data
        CPR_number = form.CPR_number.data
        update_CheckingAccount(amount, CPR_number)
        flash('Succeed!', 'success')
        return redirect(url_for('Login.home'))
    return render_template('deposit.html', title='Deposit', form=form)

@Customer.route("/summary", methods=['GET', 'POST'])
def summary():
    if not current_user.is_authenticated:
        flash('Please Login.','danger')
        return redirect(url_for('Login.login'))
    if form.validate_on_submit():
        pass
        flash('Succeed!', 'success')
        return redirect(url_for('Login.home'))
    return render_template('deposit.html', title='Deposit', form=form)

UIS_Prototype_v1/UIS_Prototype-master/bank/Employee/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from bank import app, conn, bcrypt
from bank.forms import TransferForm, DepositForm, AddCustomerForm
from flask_login import current_user
from bank.models import Transfers, CheckingAccount, InvestmentAccount, select_emp_cus_accounts, transfer_account, insert_Customers
import sys, datetime

Employee = Blueprint('Employee', __name__)

@Employee.route("/addcustomer", methods=['GET', 'POST'])
def addcustomer():
    #if current_user.is_authenticated:
    #    return redirect(url_for('Login.home'))
    form = AddCustomerForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        name=form.username.data
        CPR_number=form.CPR_number.data
        password=hashed_password
        insert_Customers(name, CPR_number, password)
        flash('Account has been created! The customer is now able to log in', 'success')
        return redirect(url_for('Login.home'))
    return render_template('addcustomer.html', title='Add Customer', form=form)


@Employee.route("/manageCustomer", methods=['GET', 'POST'])
def manageCustomer():
    if not current_user.is_authenticated:
        flash('Please Login.','danger')
        return redirect(url_for('Login.login'))
    form = TransferForm()
    if form.validate_on_submit():
        amount=form.amount.data
        cur = conn.cursor()
        sql = """
        UPDATE CheckingAccount
        SET amount = %s
        WHERE CPR_number = %s
        """ 
        cur.execute(sql, (amount, CPR_number))
        conn.commit()
        cur.close()
        flash('Transfer succeed!', 'success')
        return redirect(url_for('Login.home'))
    return render_template('transfer.html', title='Transfer', form=form)


@Employee.route("/transfer", methods=['GET', 'POST'])
def transfer():
    if not current_user.is_authenticated:
        flash('Please Login.','danger')
        return redirect(url_for('Login.login'))
    CPR_number = current_user.get_id()
    print(CPR_number)
    dropdown_accounts = select_emp_cus_accounts(current_user.get_id())
    drp_accounts = []
    for drp in dropdown_accounts:
        drp_accounts.append((drp[3], drp[1]+' '+str(drp[3])))
    print(drp_accounts)
    form = TransferForm()
    form.sourceAccount.choices = drp_accounts    
    form.targetAccount.choices = drp_accounts    
    if form.validate_on_submit():
        date = datetime.date.today()
        amount = form.amount.data
        from_account = form.sourceAccount.data
        to_account = form.targetAccount.data
        transfer_account(date, amount, from_account, to_account)
        flash('Transfer succeed!', 'success')
        return redirect(url_for('Login.home'))
    return render_template('transfer.html', title='Transfer', drop_cus_acc=dropdown_accounts, form=form)

UIS_Prototype_v1/UIS_Prototype-master/bank/Login/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from bank import app, conn, bcrypt
from bank.forms import CustomerLoginForm, EmployeeLoginForm
from flask_login import login_user, current_user, logout_user, login_required
from bank.models import Customers, select_Customers, select_Employees

Login = Blueprint('Login', __name__)

posts = [{}]


@Login.route("/")
@Login.route("/home")
def home():
    return render_template('home.html', posts=posts)


@Login.route("/about")
def about():
    return render_template('about.html', title='About')


@Login.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('Login.home'))
    is_employee = True if request.args.get('is_employee') == 'true' else False
    form = EmployeeLoginForm() if is_employee else CustomerLoginForm()
    if form.validate_on_submit():
        user = select_Employees(form.id.data) if is_employee else select_Customers(form.id.data)
        if user != None and bcrypt.check_password_hash(user[2], form.password.data):
            login_user(user, remember=form.remember.data)
            flash('Login successful.','success')
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('Login.home'))
        else:
            flash('Login Unsuccessful. Please check identifier and password', 'danger')
    return render_template('login.html', title='Login', is_employee=is_employee, form=form)


@Login.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('Login.home'))


@Login.route("/account")
@login_required
def account():
    return render_template('account.html', title='Account')

UIS_Prototype_v1/UIS_Prototype-master/bank/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>About Page</h1>
	<p>This is the UIS prototype brought to you by the UIS team 2018/19.</p>
	<ul>
		<li>Ziming Lou</li>
		<li>Lasse Pedersen</li>
		<li>Jan Rolandsen</li>
		<li>Hubert Dariusz Zajac</li>
		<li>Marco Ugo Gambetta</li>
		<li>Anders Lassen</li>
		<li>Finn Kensing</li>
		<li>Marcos Vas Salles</li>
	</ul>
	<p>You can register new customer accounts, but employee accouns must be entered by making your changes to the DML-script schema_ins.sql. To log in we have created some test accounts. The customer login can be accesed using a customer cpr in ranges 5001 to 5007 with the token 'UIS' in capital. The employee login can be accessed using employee id 6001..6007 and the same token.</p>
	<p>To add more sample data make your changes to the DML-script schema_ins.sql.</p>
	<p>The prototype is vertical. We have implemented some functions and not completed. The prototype provides a starting point for your work.</p> 
	<p>AL20190501</p>
{% endblock content %}

UIS_Prototype_v1/UIS_Prototype-master/bank/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <h1>{{ current_user.name }}</h1>
{% endblock content %}

UIS_Prototype_v1/UIS_Prototype-master/bank/templates/addcustomer.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Add a new customer</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.CPR_number.label(class="form-control-label") }}
                    {% if form.CPR_number.errors %}
                        {{ form.CPR_number(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.CPR_number.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.CPR_number(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have An Account? <a class="ml-2" href="{{ url_for('Login.login') }}">Sign In</a>
        </small>
    </div>
{% endblock content %}

UIS_Prototype_v1/UIS_Prototype-master/bank/templates/graph.html
{% extends "layout.html" %}
{% block content %}

<div class="content-section">
	<form method="POST" action="">
		<div class="form-group">
			{{ if 0 == 0 }}

	</div>
</div>


	
{% endblock content %}

UIS_Prototype_v1/UIS_Prototype-master/bank/templates/home.html
{% extends "layout.html" %}
{% block content %}
    <h1>{{ current_user.name }}</h1>
    {% for post in posts %}
        <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="#">{{ post.author }}</a>
              <small class="text-muted">{{ post.date_posted }}</small>
            </div>
            <h2><a class="article-title" href="#">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
{% endblock content %}

UIS_Prototype_v1/UIS_Prototype-master/bank/templates/invest.html
{% extends "layout_acc.html" %}
{% block content %}
    <h1>{{ current_user.name }}</h1>
	

  <div class="content-section">	
    <p>Investment accounts:</p>
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">account_number</th>
          <th scope="col">cpr_number</th>
          <th scope="col">account created</th>
          <th scope="col">deposit total (CD)</th>
        </tr>
      </thead>
      <tbody>
      {% for n in inv_sums %}
        <tr>
          <th scope="row">{{n[0]}}</th>
          <td>{{n[1]}}</td>
          <td>{{n[2]}}</td>
          <td>{{n[3]}}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>  
  </div>
  <div class="content-section">	
    <p>Investment certificats of deposit:</p>
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">acc</th>
          <th scope="col">cd_number</th>
          <th scope="col">start_date</th>
          <th scope="col">maturity_date</th>
          <th scope="col">rate</th>
          <th scope="col">amount</th>
        </tr>
      </thead>
      <tbody>
      {% for n in inv_cd_list %}
        <tr>
          <th scope="row">{{n[0]}}</th>
          <td>{{n[3]}}</td>
          <td>{{n[4]}}</td>
          <td>{{n[5]}}</td>
          <td>{{n[6]}}</td>
          <td>{{n[7]}}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>  
  </div>

	
{% endblock content %}

UIS_Prototype_v1/UIS_Prototype-master/bank/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>UIS Prototype - {{ title }}</title>
    {% else %}
        <title>UIS Prototype</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">UIS Prototype</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('Login.home') }}">Home</a>
              {% if current_user.is_authenticated %}
                <li class="dropdown">
                 <a href="#" class="nav-item nav-link dropdown-toggle" data-toggle="dropdown">UIS bank<b class="caret"></b></a>
                 <ul class="dropdown-menu">
                    <li><a class="nav-item nav-link" href="{{ url_for('Login.account') }}">Account</a></li>
                    <li><a class="nav-item nav-link" href="{{ url_for('Employee.transfer') }}">Transfer</a></li>
                    <li class="divider"></li>
                    <li><a class="nav-item nav-link" href="{{ url_for('Customer.invest') }}">Investments</a></li>
                    <li class="divider"></li>
                    <li><a class="nav-item nav-link" href="https://www.pgadmin.org">site pgAdmin</a></li>
                    <li><a class="nav-item nav-link" href="http://127.0.0.1:58653/browser/ ">pgAdmin4</a></li>
                 </ul>
               </li>
              {% else %}
              {% endif %}
              <a class="nav-item nav-link" href="{{ url_for('Login.about') }}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('Login.account') }}">Account</a>
                <a class="nav-item nav-link" href="{{ url_for('Employee.addcustomer') }}">Add customer</a>
                <a class="nav-item nav-link" href="{{ url_for('Employee.transfer') }}">Transfer</a>
                <a class="nav-item nav-link" href="{{ url_for('Customer.invest') }}">Investments</a>
                <a class="nav-item nav-link" href="{{ url_for('Login.logout') }}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('Login.login') }}">Login</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Account</h3>
              <ul class="list-group">
              {% if current_user.is_authenticated %}
                <li class="list-group-item list-group-item-light"><a class="nav-item nav-link" href="{{ url_for('Employee.transfer') }}">Transfer</a></li>
                <li class="list-group-item list-group-item-light">Checking Accounts</li>
                <li class="list-group-item list-group-item-light">Investment Accounts</li>
                <li class="list-group-item list-group-item-light"><a class="nav-item nav-link" href="{{ url_for('Customer.invest') }}">View investment accounts</a></li>
                <li class="list-group-item list-group-item-light">etc</li>
              {% else %}
                <li class="list-group-item list-group-item-light">etc</li>
              {% endif %}
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

UIS_Prototype_v1/UIS_Prototype-master/bank/templates/layout_acc.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>UIS Prototype - {{ title }}</title>
    {% else %}
        <title>UIS Prototype</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">UIS Prototype</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('Login.home') }}">Home</a>
              {% if current_user.is_authenticated %}
                <li class="dropdown">
                 <a href="#" class="nav-item nav-link dropdown-toggle" data-toggle="dropdown">UIS bank<b class="caret"></b></a>
                 <ul class="dropdown-menu">
                    <li><a class="nav-item nav-link" href="{{ url_for('Login.account') }}">Account</a></li>
                    <li><a class="nav-item nav-link" href="{{ url_for('Employee.transfer') }}">Transfer</a></li>
                    <li class="divider"></li>
                    <li><a class="nav-item nav-link" href="{{ url_for('Customer.invest') }}">Investments</a></li>
                    <li class="divider"></li>
                    <li><a class="nav-item nav-link" href="https://www.pgadmin.org">site pgAdmin</a></li>
                    <li><a class="nav-item nav-link" href="http://127.0.0.1:58653/browser/ ">pgAdmin4</a></li>
                 </ul>
               </li>
              {% else %}
              {% endif %}
               <a class="nav-item nav-link" href="{{ url_for('Login.about') }}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('Login.account') }}">Account</a>
                <a class="nav-item nav-link" href="{{ url_for('Employee.transfer') }}">Transfer</a>
                <a class="nav-item nav-link" href="{{ url_for('Customer.invest') }}">Investments</a>
                <a class="nav-item nav-link" href="{{ url_for('Login.logout') }}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('Login.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('Employee.addcustomer') }}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Account</h3>
              <ul class="list-group">
                <li class="list-group-item list-group-item-light"><a class="nav-item nav-link" href="{{ url_for('Employee.transfer') }}">Transfer</a></li>
                <li class="list-group-item list-group-item-light">Checking Accounts</li>
                <li class="list-group-item list-group-item-light">Investment Accounts</li>
                <li class="list-group-item list-group-item-light"><a class="nav-item nav-link" href="{{ url_for('Customer.invest') }}">View investment accounts</a></li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

UIS_Prototype_v1/UIS_Prototype-master/bank/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.id.label(class="form-control-label") }}
                    {% if form.id.errors %}
                        {{ form.id(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.id.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.id(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
            <small class="text-muted">
                <a href="#">Forgot Password?</a>
            </small>
            <small class="text-muted ml-2">
                {% if is_employee %}
                    <a href="/login?is_employee=false">Customer login?</a>
                {% else %}
                    <a href="/login?is_employee=true">Employee login?</a>
                {%  endif %}
            </small>
        </form>
    </div>
{% endblock content %}

UIS_Prototype_v1/UIS_Prototype-master/bank/templates/transfer.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <div class="form-group">
                {{ form.sourceAccount.label(class="form-control-label") }}
                {{ form.sourceAccount(class="form-control")}}
            </div>
            <fieldset class="form-group">
                <div class="form-group">
                    {{ form.amount.label(class="form-control-label") }}
                    {% if form.amount.errors %}
                        {{ form.amount(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.amount(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.targetAccount.label(class="form-control-label") }}
                {{ form.targetAccount(class="form-control") }}
            </div>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
	
    <div class="content-section">	
      <p>dropdown cusrtomer account tuples:</p>
      <ul class="list-group">
        {% for n in drop_cus_acc %}
        <li class="list-group-item list-group-item-light">{{n}}}</li>
        {% endfor %}
      </ul>
      <br>
      <p>Same list with a filter: {{ drop_cus_acc|join(', ') }}</p>
    </div>
	
{% endblock content %}